name: Build-APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 3️⃣ Android SDK & licences
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          ndk: false
          cache: gradle

      # 4️⃣ Gradle 8.7 (compatible with AGP 8.4+)
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.7'

      # 5️⃣ Build APK
      - name: Build Debug APK
        run: gradle assembleDebug

      # 6️⃣ Upload artefact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AccidentDetection-debug
          path: app/build/outputs/apk/debug/app-debug.apk
